openapi: 3.0.1
info:
  title: Go App
  description: 'This is a sample go server'
  contact:
    email: law@zava.dev
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /ping:
    get:
      tags:
        - pinger
      summary: Pings server
      responses:
        200:
          description: Success